server:
  port: 9000

spring:
  cloud:
    stream:
      bindings:
        input:
          destination: learning-spring-boot1
          group: comments
          content-type: application/json
        output:
          destination: learning-spring-boot1
  application:
    name: comments